tkCategories = {
    "NUM_REAL" : r"^\d+(\.\d+)$|^-\d+(\.\d+)$",
    "NUM_INT" : r"^-[0-9]*|[0-9]*",
    "CADEIA " : r'"[^”]*"',
    "FIM" : "",
    "FUNC_NAME": r'(FUNC)[^a-zA-Z0-9_]',
    "VAR": r'^[$][a-zA-Z0-9_]*',
    "VECTOR": r'^[@][a-zA-Z0-9_]*',
    "OPERATOR_LT_NUMERIC": r'<',
    "OPERATOR_GT_NUMERIC" : r'>',
    "OPERATOR_PLUS_PLUS" : r'\+\+',
    "OPERATOR_MINUS_MINUS" : r'--',
    "OPERATOR_AND": r'&&',
    "OPERATOR_OR" : r'\|\|',
    "OPERATOR_NOT": r'!',
    "OPERATOR_DIV" : r'/',
    "OPERATOR_MUL" : r'\*',
    "OPERATOR_MOD" : r'\%',
    "OPERATOR_PLUS" : r'\+',
    "OPERATOR_MINUS": r'\-',
    "OPERATOR_GE_NUMERIC" : r'>=',
    "OPERATOR_LE_NUMERIC": r'<=',
    "OPERATOR_EQ_NUMERIC": r'==',
    "OPERATOR_NE_NUMERIC" : r'!=',
    "OPERATOR_ASSIGN": r'=',
    "LEFT_PAREN": r'\(',
    "RIGHT_PAREN": r'\)',
    "LEFT_BRACE": r'\{',
    "RIGHT_BRACE" : r'\}',
    "SEMICOLON": r';',
    "RESERVED_IF": r'if',
    "RESERVED_ELSIF" : r'elsif',
    "RESERVED_ELSE" : r'else',
    "RESERVED_WHILE" : r'while',
    "RESERVED_DEFAULT" : r'default',
    "RESERVED_ASYNC" : r'async',
    "RESERVED_PACKAGE" : r'package',
    "RESERVED_USE" : r'use',
    "RESERVED_PRINT" : r'print',
    "RESERVED_SAY" : r'say',
    "RESERVED_TRY" : r'try',
    "RESERVED_CATCH" : r'catch',
    "RESERVED_SWITCH" : r'switch',
    "RESERVED_CASE" : r'case',
    "RESERVED_RETURN" : r'return',
    "RESERVED_EXIT" : r'exit',
    "RESERVED_METHOD" : r'method',
    "RESERVED_FUNC" : r'func'
}